import pickle
import numpy as np
from tensorflow.keras.models import load_model
from music21 import instrument, note, stream, chord

def generate_notes(model, network_input, note_to_int, n_vocab, num_generate=200):
    """ Generate notes from the neural network based on a sequence of notes """
    
    int_to_note = dict((number, note) for note, number in note_to_int.items())
    
    # pick a random sequence from the input as a starting point for the generation
    start = np.random.randint(0, len(network_input)-1)
    
    pattern = network_input[start]
    prediction_output = []
    
    # We need to extract the actual integers because they were normalized in preprocess.py
    # So we'll multiply back by n_vocab to get integers, but wait, network_input has normalized values
    # Actually, pattern is of shape (sequence_length, 1) and values are normalized.
    # Let's extract the seed pattern
    
    print(f"Generating {num_generate} notes...")
    for note_index in range(num_generate):
        prediction_input = np.reshape(pattern, (1, len(pattern), 1))
        
        prediction = model.predict(prediction_input, verbose=0)
        
        index = np.argmax(prediction)
        result = int_to_note[index]
        prediction_output.append(result)
        
        # Append the new prediction to the pattern, properly normalized
        # and remove the first element to slide the window
        pattern = np.vstack((pattern[1:], [[index / float(n_vocab)]]))
        
        if (note_index + 1) % 50 == 0:
            print(f"Generated {note_index + 1} notes")
            
    return prediction_output

def create_midi(prediction_output, filename='generated_music.mid'):
    """ convert the output from the prediction to notes and create a midi file from the notes """
    offset = 0
    output_notes = []

    # create note and chord objects based on the values generated by the model
    for pattern in prediction_output:
        # pattern is a chord
        if ('.' in pattern) or pattern.isdigit():
            notes_in_chord = pattern.split('.')
            notes = []
            for current_note in notes_in_chord:
                new_note = note.Note(int(current_note))
                new_note.storedInstrument = instrument.Piano()
                notes.append(new_note)
            new_chord = chord.Chord(notes)
            new_chord.offset = offset
            output_notes.append(new_chord)
        # pattern is a note
        else:
            new_note = note.Note(pattern)
            new_note.offset = offset
            new_note.storedInstrument = instrument.Piano()
            output_notes.append(new_note)

        # increase offset each iteration so that notes do not stack
        offset += 0.5

    midi_stream = stream.Stream(output_notes)
    midi_stream.write('midi', fp=filename)
    print(f"Saved generated music to {filename}")

if __name__ == '__main__':
    print("Loading data...")
    try:
        with open('data.pkl', 'rb') as filepath:
            data = pickle.load(filepath)
            
        network_input = data['network_input']
        note_to_int = data['note_to_int']
        n_vocab = data['n_vocab']
        
        print("Loading trained model...")
        model = load_model('music_gen_model.keras')
        
        prediction_output = generate_notes(model, network_input, note_to_int, n_vocab)
        create_midi(prediction_output)
        
    except FileNotFoundError:
        print("Error: data.pkl or model file not found. Ensure you have run preprocess.py and train.py.")
